---
- name: Wazuh installation 
  hosts: local
  remote_user: piet	
  
  tasks:
  - name: Download foo.conf
    get_url:
      url: "{{ item }}"
      dest: /home/piet/local_wazuh
      mode: '0440'
	
	

  - name: Write the apache config file
    ansible.builtin.template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf

- name: Update db servers
  hosts: databases
  remote_user: root

  tasks:
  - name: Ensure postgresql is at the latest version
    ansible.builtin.yum:
      name: postgresql
      state: latest
  - name: Ensure that postgresql is started
    ansible.builtin.service:
      name: postgresql
      state: started