---
- name: Wazuh installation 
  hosts: local
  gather_facts: no
  ignore_errors: yes
  remote_user: piet
  
  roles:
    - wazuh_indexer
    - wazuh_server
    
  vars_files:
    - pass.yml



  