---
- name: Wazuh unattended installation 
  hosts: local # replace with hostname or group
  gather_facts: no # for performance means only
#  ignore_errors: yes
  remote_user: piet #replace with user
  
  tasks: 
  - name: Create directories
    ansible.builtin.file:
      path: /home/piet/wazuh_unat #directory for downloading, change as needed
      state: directory
      mode: '0755'

  - name: Downloading Wazuh
    become: yes
    get_url:
      url: https://packages.wazuh.com/4.3/wazuh-install.sh
      dest: /home/piet/wazuh_unat #match with above created directory

  - name: Script uitvoeren
    become: yes
    ansible.builtin.shell: bash /home/piet/wazuh_unat/wazuh-install.sh -a