
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
      - /home/piet/wazuh_install
      - /home/piet/wazuh_install/indexer

- name: Download Certificates & Config
  get_url:
    url: https://packages.wazuh.com/4.3/wazuh-certs-tool.sh
    dest: /home/piet/wazuh_install/indexer

- name: Store script on controller
  ansible.builtin.fetch:
    src: /home/piet/wazuh_install/indexer/wazuh-certs-tool.sh
    dest: /home/piet/local_wazuh/wazuh-certs-tool.sh

- name: Copy config
  ansible.builtin.copy:
    src: /home/piet/local_wazuh/config.yml
    dest: /home/piet/wazuh_install/indexer
    mode: '0755'

- name: Script uitvoeren
  ansible.builtin.shell: bash /home/piet/wazuh_install/indexer/wazuh-certs-tool.sh -A

- name: TAR 
  ansible.builtin.shell: tar -cvf /home/piet/wazuh_install/indexer/wazuh-certificates.tar -C /home/piet/wazuh_install/indexer/wazuh-certificates/ .
